// <auto-generated />
namespace HMS_PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblUserRole_20211127 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblUserRole_20211127));
        
        string IMigrationMetadata.Id
        {
            get { return "202111262133516_tblUserRole_20211127"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
